### ISSUE TITLE
博主您好，尝试测试您的Demo，但是一直卡在face_detector.detect(image, landmarks=True)无法执行 #2

### ISSUE THREAD

**Issue by 821029883** [chengzhengxin/deep-sdm#3]
![图片](https://user-images.githubusercontent.com/52727204/89701816-167a5500-d96d-11ea-8bef-e47bfc25d536.png)

一直卡在face_detector.detect(image, landmarks=True)无法执行，想问下您使用的torch及torchvision版本号是？

**Comment by chengzhengxin** [comment]
![image](https://user-images.githubusercontent.com/13405040/89702893-509d2400-d978-11ea-95cd-8c1174b85e3d.png)

torch. 1.4.0
torchvision  0.5.0

**Comment by 821029883** [comment]
谢谢您的回答，更换torch版本后，Demo运行还是卡在
![图片](https://user-images.githubusercontent.com/52727204/89703362-788e8680-d97c-11ea-834e-408cc494bfaf.png)

想问下博主对输入图片尺寸是否有要求呢，我读取的是摄像头输入的图片。
![图片](https://user-images.githubusercontent.com/52727204/89703375-a247ad80-d97c-11ea-9dbc-1d4d96043c0f.png)

是否需要resize到特定尺寸？

**Comment by 821029883** [comment]
谢谢您，找到原因了，未操作显示图片，感谢博主回答。
